// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for posts documents */
type PostsDocumentData = Record<string, never>;
/**
 * posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<PostsDocumentData>, "posts", Lang>;
/** Content for Page documents */
type SlugDocumentData = Record<string, never>;
/**
 * Page document from Prismic
 *
 * - **API ID**: `slug`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SlugDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SlugDocumentData>, "slug", Lang>;
export type AllDocumentTypes = PostsDocument | SlugDocument;
/**
 * Primary content in Po → Primary
 *
 */
interface PoSliceDefaultPrimary {
    /**
     * Title field in *Po → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: po.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Po → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: po.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Po Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Po`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PoSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Po*
 *
 */
type PoSliceVariation = PoSliceDefault;
/**
 * Po Shared Slice
 *
 * - **API ID**: `po`
 * - **Description**: `Po`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PoSlice = prismicT.SharedSlice<"po", PoSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PostsDocumentData, PostsDocument, SlugDocumentData, SlugDocument, AllDocumentTypes, PoSliceDefaultPrimary, PoSliceDefault, PoSliceVariation, PoSlice };
    }
}
